@startuml

    actor Attore
    boundary Carrello
    entity Attore as AttoreE

    activate Attore
    activate AttoreE
    activate Carrello
    Attore -> Carrello : pushButton(modificaQuantitaProdotto)
    Carrello -> Carrello : changeQuantita()
    activate Carrello
    Attore -> Carrello : insertData(quantita)
    Attore -> Carrello : pressButton(conferma)
    Carrello -> AttoreE : modificaQuantitaCarrello(prodotto, quantita)
    AttoreE --> Carrello : false 
    Carrello -> Carrello : message(quantita maggiore del catalogo)
    deactivate Carrello
@enduml