@startuml

    actor Assistenza
    boundary HomePage
    control Redirect
    boundary StatoOrdine
    entity Assistenza as AssistenzaE


    activate Assistenza 
    activate AssistenzaE
    Assistenza -> HomePage : insertData(codiceFattura)
    Assistenza -> HomePage : buttonPressed(cerca)
    activate HomePage
    HomePage -> Redirect : chandePage(fattura)
    activate Redirect    
    Redirect -> StatoOrdine : display()
    deactivate HomePage
    deactivate Redirect
    activate StatoOrdine

    StatoOrdine -> AssistenzaE : getFattura()
    AssistenzaE -> StatoOrdine : data
@enduml