@startuml

    actor DirettoreGenerale
    boundary HomePage
    control Credenziali
    entity DirettoreGenerale as DirettoreGeneraleE


    activate DirettoreGenerale 
    activate DirettoreGeneraleE
    activate HomePage
    DirettoreGenerale -> HomePage : insertData(emailAziendale)
    activate HomePage
    HomePage -> Credenziali : checkEmailAziendale(emailAziendale)
    activate Credenziali
    Credenziali --> HomePage : true
    deactivate Credenziali
    DirettoreGenerale -> HomePage : insertData(nome, cognome, dataNascita, DirettoreMagazzino)
    DirettoreGenerale -> HomePage : buttonPressed(inserisci)
    HomePage -> DirettoreGeneraleE : insertAddetto(data)
    DirettoreGeneraleE --> HomePage : true
    HomePage -> HomePage
    deactivate HomePage

@enduml