@startuml

    actor DirettoreMagazzino
    boundary HomePage
    control Redirect
    boundary Scaffale
    entity DirettoreMagazzino as DirettoreMagazzinoE


    activate DirettoreMagazzino 
    activate DirettoreMagazzinoE
    activate HomePage
    DirettoreMagazzino -> HomePage : insertScaffale()
    HomePage -> Redirect : changePage(insertScaffale)
    deactivate HomePage
    activate Redirect
    Redirect -> Scaffale : display()
    deactivate Redirect
    activate Scaffale 
    DirettoreMagazzino -> Scaffale : insertData(nome, posti)
    DirettoreMagazzino -> Scaffale : buttonPressed(salva)
    Scaffale -> DirettoreMagazzinoE : insertNuovoScaffale(data)
    DirettoreMagazzinoE --> Scaffale : true


@enduml