package com.birdcomics.Unit;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void rimozionedelcarrello() {
    driver.get("http://localhost:8080/BirdComics/");
    driver.manage().window().setSize(new Dimension(1942, 1053));
    driver.findElement(By.linkText("Login")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("email")).sendKeys("cliente@example.com");
    driver.findElement(By.id("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.cssSelector(".col-sm-4:nth-child(1) .btn")).click();
    driver.findElement(By.name("pqty")).sendKeys("5");
    driver.findElement(By.name("pqty")).click();
    driver.findElement(By.name("Update")).click();
    driver.findElement(By.name("pqty")).sendKeys("4");
    driver.findElement(By.name("pqty")).click();
    driver.findElement(By.name("Update")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) button")).click();
    driver.findElement(By.linkText("Home")).click();
  }
}
